# pnpm workspace 配置
# 定义 workspace 中包含的包路径
# 所有列出的路径下的 package.json 都会被识别为 workspace 包
packages:
    # 原有 Gauzy 包（作为参考保留）
    - 'apps/*'
    - 'packages/*'
    - 'packages/plugins/*'
    - 'tools'

    # 新项目结构（@oksai/ 前缀）
    - 'libs/auth'
    - 'libs/core'
    - 'libs/plugin'
    - 'libs/*'
    - 'apps/base-api'

# pnpm Catalog - 统一管理依赖版本
# 参考: https://pnpm.io/zh/catalogs
# Catalog 是 pnpm 推荐的依赖版本管理方式，相比 overrides 有以下优势：
# 1. 维护唯一版本 - 确保工作空间中共同依赖项版本一致
# 2. 易于更新 - 只需编辑 catalog 定义，无需修改所有 package.json
# 3. 减少合并冲突 - 依赖版本更新时不会发生 git 冲突
# 4. 支持多个版本集合 - 可以为不同场景定义不同的版本

# 默认 catalog（使用 catalog: 或 catalog:default 引用）
catalog:
    # gRPC
    '@grpc/grpc-js': '^1.7.3'

    # NestJS 核心依赖
    '@nestjs/common': '^11.1.12'
    '@nestjs/core': '^11.1.12'
    '@nestjs/typeorm': '^11.0.0'
    '@nestjs/swagger': '^11.2.5'
    '@nestjs/cqrs': '^11.0.3'
    '@nestjs/config': '^4.0.2'
    '@nestjs/platform-express': '^11.1.12'
    '@nestjs/cache-manager': '^3.1.0'
    '@nestjs/passport': '^11.0.5'
    '@nestjs/mapped-types': '^2.1.0'
    '@nestjs/terminus': '^11.0.0'
    '@nestjs/graphql': '^13.2.3'
    '@nestjs/schematics': '^11.0.9'
    '@nestjs/testing': '^11.1.12'
    '@nestjs/axios': '^4.0.1'
    '@nestjs/schedule': '^5.0.1'

    # MikroORM
    '@mikro-orm/nestjs': '^6.1.1'
    '@mikro-orm/core': '^6.6.5'
    '@mikro-orm/better-sqlite': '^6.6.5'
    '@mikro-orm/postgresql': '^6.6.5'
    '@mikro-orm/mysql': '^6.6.5'

    # TypeORM
    'typeorm': '^0.3.28'

    # 验证和转换
    'class-validator': '^0.14.2'
    'class-transformer': '^0.5.1'

    # 工具库
    'chalk': '^4.1.0'
    'connect-redis': '^7.1.0'
    'express': '^5.2.1'
    'express-session': '^1.18.0'
    'helmet': '^8.1.0'
    'moment': '^2.30.1'
    'moment-timezone': '^0.6.0'
    'redis': '^5.10.0'
    'tslib': '^2.3.0'
    'rxjs': '^7.8.2'
    'reflect-metadata': '^0.2.2'

    # OpenTelemetry
    '@opentelemetry/api': '^1.9.0'
    '@opentelemetry/sdk-node': '^0.56.0'
    '@opentelemetry/sdk-trace-base': '^1.26.0'
    '@opentelemetry/resources': '^1.26.0'
    '@opentelemetry/semantic-conventions': '^1.27.0'
    '@opentelemetry/auto-instrumentations-node': '^0.52.0'
    '@opentelemetry/instrumentation-http': '^0.56.0'
    '@opentelemetry/instrumentation-express': '^0.46.0'
    '@opentelemetry/instrumentation-nestjs-core': '^0.39.0'
    '@opentelemetry/instrumentation-redis': '^0.42.0'
    '@opentelemetry/instrumentation-pg': '^0.48.0'
    '@opentelemetry/instrumentation-mysql2': '^0.41.0'
    '@opentelemetry/exporter-trace-otlp-http': '^0.57.0'
    '@opentelemetry/exporter-trace-otlp-grpc': '^0.57.0'
    '@opentelemetry/exporter-zipkin': '^1.26.0'
    '@honeycombio/opentelemetry-node': '^0.7.2'

    # 队列和任务
    '@nestjs/bullmq': '^11.0.4'
    'bullmq': '^5.26.2'

    # 模板引擎
    'handlebars': '^4.7.8'

    # GraphQL
    'graphql': '^16.11.0'
    '@apollo/server': '^4.12.0'
    '@apollo/client': '^3.13.8'

    # 类型定义
    '@types/express': '^5.0.1'
    '@types/node': '^24.10.0'
    '@types/passport-google-oauth20': '^2.0.16'
    '@types/passport-github2': '^1.2.9'
    '@types/passport-auth0': '^1.0.9'
    '@types/passport-microsoft': '^2.1.1'
    '@types/jest': '^29.5.14'

    # 开发工具
    'jest': '^29.7.0'
    'typescript': '^5.8.0'
    'ts-node': '^10.9.2'
    'ts-jest': '^29.4.6'
    'cross-env': '^10.1.0'
    'dotenv': '^17.2.3'
    'yargs': '^17.5.0'
    'rimraf': '^3.0.2'
    'nodemon': '^3.1.0'

# 具名 catalogs（可选，用于不同场景）
# 可以通过 "catalog:name" 引用，例如 "catalog:prod" 或 "catalog:dev"
catalogs:
    # 生产依赖版本目录
    prod:
        '@grpc/grpc-js': '^1.7.3'
        '@nestjs/common': '^11.1.12'
        '@nestjs/core': '^11.1.12'
        '@nestjs/typeorm': '^11.0.0'
        '@nestjs/swagger': '^11.2.5'
        '@nestjs/cqrs': '^11.0.3'
        '@nestjs/config': '^4.0.2'
        '@nestjs/platform-express': '^11.1.12'
        '@nestjs/cache-manager': '^3.1.0'
        '@nestjs/passport': '^11.0.5'
        '@nestjs/mapped-types': '^2.1.0'
        '@nestjs/terminus': '^11.0.0'
        '@nestjs/graphql': '^13.2.3'
        '@mikro-orm/nestjs': '^6.1.1'
        '@mikro-orm/core': '^6.6.5'
        '@mikro-orm/better-sqlite': '^6.6.5'
        '@mikro-orm/postgresql': '^6.6.5'
        '@mikro-orm/mysql': '^6.6.5'
        'typeorm': '^0.3.28'
        'class-validator': '^0.14.2'
        'class-transformer': '^0.5.1'
        'chalk': '^4.1.0'
        'moment': '^2.30.1'
        'moment-timezone': '^0.6.0'
        'tslib': '^2.3.0'
        'rxjs': '^7.8.2'
        'reflect-metadata': '^0.2.2'
        'graphql': '^16.11.0'
        '@apollo/server': '^4.12.0'
        '@apollo/client': '^3.13.8'
        'dotenv': '^17.2.3'
        'yargs': '^17.5.0'

    # 开发依赖版本目录
    dev:
        '@nestjs/schematics': '^11.0.9'
        '@nestjs/testing': '^11.1.12'
        '@types/express': '^5.0.1'
        '@types/node': '^24.10.0'
        '@types/passport-google-oauth20': '^2.0.16'
        '@types/passport-github2': '^1.2.9'
        '@types/passport-auth0': '^1.0.9'
        '@types/jest': '^29.5.14'
        'jest': '^29.7.0'
        'typescript': '^5.8.0'
        'ts-node': '^10.9.2'
        'ts-jest': '^29.4.6'
        'cross-env': '^10.1.0'
        'rimraf': '^3.0.2'
        'nodemon': '^3.1.0'
